---
title: "RWorksheet_Cabico#2"
author: "Krestal Joy Cabico"
date: "2023-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r 1a}
#1.Generate a sequence from -5 to 5.

#If i use the:operator,the output will be 1 to 11,but if i change:
seq(-5,5, by=1)

sequence <- seq(-5:5)
sequence
```
```{r 1b}
#b.What will be the value of x?
#Value of will be a sequence from 1 to 7
x <- 1:7
x
```
```{r 2}
#2.Create a vector using seq() function
#Output : [1] 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.2, 2.4, 2.6, 2.8, 3.0
#The numbers are sequence but in 0.2 interval
seq(1,3, by=0.2)

```
```{r 3a}
#Create a vector of workers' age in a factory
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57,
         49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 38,
         41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
#a Access 3rd element, what is the value?
element_3 <- age[3]
element_3
```
```{r 3b}
#b Access 2nd and 4th element , what are the values?
element_2 <- age[2]
element_4 <- age[4]
element_2
element_4
```
```{r 3c}
#c.Access all but the 4th and 12th element is not included.Write the R script and its output
#Element 4 is 36 while element 12 is 31.
new_age <- age[-4]
new_age
```
```{r 3d}
new_age <- age[-12]
new_age
```

```{r 4a}
#4.*Create a vector x <- c("first"=3, "second"=0, "third"=9). Then name the vector, names(x)

names <- c("first"=3, "second"=0, "third"=9)
names
```
```{r 4b}
#a.Print the results. Then access x[c("first", "third",)].
#Output: first  third
#           3      9
names[c("first", "third")]
```
```{r 5a}
#5.Create a sequence x from -3:2.
#output [1] 1 2 3 4 5 6
sequence <- (-3:2)
sequence
```
```{r 5b}
#a.Modify 2nd element and change it to 0;
x[2] <- 0
x
```

```{r 6a}
#6.Create a data frame for month, price per liter (php) and purchase-quantity (liter).
#Create a data frame directly
diesel <- data.frame(
  Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
  Price_Per_Liter = c(52.50, 57.50, 60.00, 65.00, 74.25, 54.00),
  Purchase_quantity = c(25, 30, 40, 50, 10, 45)
)
diesel
```
```{r 6b}
#Calculate the weighted mean of fuel expenditure
average_expenditure<- weighted.mean(diesel$Price_Per_Liter, diesel$Purchase_quantity)


#Print the average expenditure
average_expenditure
```
 
```{r 7}
#7.Create a vector data with 7 elements

data <- c (length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
           sd(rivers), min(rivers), max(rivers))
data
```
#The results are: [1]    141.0000  83357.0000    591.1844    425.0000 243908.4086
#[6]    493.8708    135.0000   3710.0000

#Create vectors according to the table.
```{r 8a}
#a.Vectors using the data in the table.
Power_Ranking <- c(1:25)
TopCelebrity <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Speilberg", "Howard Stern",
 "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Sringteen", "Donald Trump", "Muhammad Ali", "Pau MacCartney", "George Lucas","Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Brad Pitt", "Peter Jackson", "Dr.Phil McGraw","Jay Lenon", "Celine Dion", "Kobe Bryant")
Annual_Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
PowerRanking <- data.frame(Power_Ranking, TopCelebrity, Annual_Pay)
PowerRanking
```

```{r 8b}
#b. Modify the power ranking and pay of J.K Rowling.Change power ranking to 15 and pay to 90.
Power_Ranking [19] <-15 
Power_Ranking
Annual_Pay [19] <- 90
Annual_Pay

```






#8
``` {r 8c}
library(readr)
Forbes <- read_csv("Forbes  .csv", show_col_types = FALSE)
Forbes
```
#9
``` {r num9a}
library(readxl)
vienna <- read_excel("vienna.xlsx")
vienna
```
``` {r num9b}
dimensions <- dim(vienna)
dimensions
```
```{r num9c}
selected_columns <- vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
head(selected_columns, n = nrow(selected_columns))
```

```{r num9d}
save(selected_columns, file = "new.RData")
```

```{r num9e}
load("new.RData")
head(selected_columns)
tail(selected_columns)
```
#10

``` {r 10a}
vegetables <- list ("Spinach",  "Eggplant", "Okra", "Winged Bean", "Carrots", "Potato","Corn", "Cabbage", "Cucumber", "Tomato")


vegetables
```

``` {r 10b}
VegetablesList <- append(vegetables,c("Monggo Beans","Lettuce"),after=10)
VegetablesList
```

``` {r 10c}
NewVegetablesList <- append(VegetablesList,c("Squash", "String Beans", "Mushrooms", "Peas"),after=5)
NewVegetablesList
```

```{r 10d}
Veggies<-NewVegetablesList[c(-5,-10,-15)]
Veggies

length(Veggies)
```